# Generated by Django 5.2.16 on 2026-08-06 06:54

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4) for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("name", models.CharField(max_length=255, verbose_name="name")),
                ("slug", models.SlugField(max_length=255, unique=True, verbose_name="slug")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="categories/", verbose_name="image"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="is active")),
                ("sort_order", models.IntegerField(default=0, verbose_name="sort order")),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="children",
                        to="categories.category",
                        verbose_name="parent category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category",
                "verbose_name_plural": "Categories",
                "ordering": ["parent__id", "sort_order"],
            },
        ),
        migrations.CreateModel(
            name="CategoryAttribute",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4) for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="attribute name")),
                (
                    "attribute_type",
                    models.CharField(
                        choices=[
                            ("text", "Text"),
                            ("number", "Number"),
                            ("boolean", "Boolean"),
                            ("select", "Select"),
                        ],
                        default="text",
                        max_length=20,
                        verbose_name="attribute type",
                    ),
                ),
                ("is_required", models.BooleanField(default=False, verbose_name="is required")),
                (
                    "is_filterable",
                    models.BooleanField(
                        default=False,
                        help_text="Used for search/catalog filters",
                        verbose_name="is filterable",
                    ),
                ),
                (
                    "is_variant",
                    models.BooleanField(
                        default=False,
                        help_text="Used to define product SKUs/variants",
                        verbose_name="is variant",
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="sort order")),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attributes",
                        to="categories.category",
                        verbose_name="category",
                    ),
                ),
            ],
            options={
                "verbose_name": "Category Attribute",
                "verbose_name_plural": "Category Attributes",
                "ordering": ["category", "sort_order"],
            },
        ),
    ]
