# Generated by Django 5.2.17 on 2026-08-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cart", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="cartitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 1)), name="cart_item_quantity_gte_1"
            ),
        ),
    ]
