# Generated by Django 5.2.17 on 2026-08-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="address",
            index=models.Index(fields=["user", "is_deleted"], name="idx_address_user_is_deleted"),
        ),
    ]
