# Generated by Django 5.2.16 on 2026-08-06 07:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4) for this record.', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
                ('order_number', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='order number')),
                ('status', models.CharField(choices=[('pending', 'Pending Payment'), ('processing', 'Processing'), ('shipped', 'Shipped'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], db_index=True, default='pending', max_length=20, verbose_name='status')),
                ('subtotal', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='subtotal (Rial)')),
                ('shipping_cost', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='shipping cost (Rial)')),
                ('discount_amount', models.DecimalField(decimal_places=0, default=0, max_digits=12, verbose_name='discount amount (Rial)')),
                ('total', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='total amount (Rial)')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='order notes')),
                ('paid_at', models.DateTimeField(blank=True, null=True, verbose_name='paid at')),
                ('cancelled_at', models.DateTimeField(blank=True, null=True, verbose_name='cancelled at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OrderAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4) for this record.', primary_key=True, serialize=False)),
                ('recipient_name', models.CharField(max_length=200, verbose_name='recipient name')),
                ('recipient_phone', models.CharField(max_length=20, verbose_name='recipient phone')),
                ('province', models.CharField(max_length=100, verbose_name='province')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('postal_code', models.CharField(max_length=20, verbose_name='postal code')),
                ('address_line', models.TextField(verbose_name='address line')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='shipping_address', to='orders.order', verbose_name='order')),
            ],
            options={
                'verbose_name': 'Order Address',
                'verbose_name_plural': 'Order Addresses',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier (UUID v4) for this record.', primary_key=True, serialize=False)),
                ('product_name', models.CharField(max_length=255, verbose_name='product name snapshot')),
                ('variant_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='variant name snapshot')),
                ('sku', models.CharField(max_length=100, verbose_name='SKU snapshot')),
                ('quantity', models.PositiveIntegerField(verbose_name='quantity')),
                ('unit_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='unit price snapshot (Rial)')),
                ('total_price', models.DecimalField(decimal_places=0, max_digits=12, verbose_name='total price snapshot (Rial)')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order', verbose_name='order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.product', verbose_name='product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='products.productvariant', verbose_name='product variant')),
            ],
            options={
                'verbose_name': 'Order Item',
                'verbose_name_plural': 'Order Items',
            },
        ),
    ]
