# Generated by Django 5.2.17 on 2026-08-29 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_order_subtotal_gte_0_and_more"),
        ("products", "0003_productcomment"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="coupon_code",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="coupon code snapshot"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="coupon_snapshot",
            field=models.JSONField(blank=True, default=dict, verbose_name="coupon snapshot"),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=0,
                default=0,
                max_digits=12,
                verbose_name="discount amount per unit (Rial)",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="original_unit_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=0,
                max_digits=12,
                null=True,
                verbose_name="original unit price snapshot (Rial)",
            ),
        ),
        migrations.AddField(
            model_name="orderitem",
            name="promotion_snapshot",
            field=models.JSONField(blank=True, default=dict, verbose_name="promotion snapshot"),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=0, max_digits=12, verbose_name="final unit price snapshot (Rial)"
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                condition=models.Q(("discount_amount__gte", 0)),
                name="order_item_discount_amount_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="orderitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("original_unit_price__isnull", True),
                    ("original_unit_price__gte", 0),
                    _connector="OR",
                ),
                name="order_item_orig_price_gte_0",
            ),
        ),
    ]
