# Generated by Django 5.2.17 on 2026-08-29 06:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("categories", "0001_initial"),
        ("orders", "0003_order_coupon_code_order_coupon_snapshot_and_more"),
        ("products", "0003_productcomment"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4) for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "code",
                    models.CharField(
                        db_index=True,
                        help_text="Unique coupon code. Stored and compared in uppercase.",
                        max_length=50,
                        unique=True,
                        verbose_name="coupon code",
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="description")),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("percentage", "Percentage"), ("fixed_amount", "Fixed Amount")],
                        max_length=20,
                        verbose_name="discount type",
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=0,
                        help_text="Percentage (0-100) when type is percentage, or fixed Rial amount when type is fixed_amount.",
                        max_digits=12,
                        verbose_name="discount value",
                    ),
                ),
                (
                    "max_discount_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        help_text="Caps the discount for percentage-type coupons.",
                        max_digits=12,
                        null=True,
                        verbose_name="maximum discount amount (Rial)",
                    ),
                ),
                (
                    "min_order_subtotal",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        help_text="Order subtotal must meet this threshold for the coupon to apply.",
                        max_digits=12,
                        verbose_name="minimum order subtotal (Rial)",
                    ),
                ),
                ("start_at", models.DateTimeField(blank=True, null=True, verbose_name="start at")),
                ("end_at", models.DateTimeField(blank=True, null=True, verbose_name="end at")),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=True, verbose_name="is active"),
                ),
                (
                    "total_usage_limit",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Maximum total redemptions. Null = unlimited.",
                        null=True,
                        verbose_name="total usage limit",
                    ),
                ),
                (
                    "per_user_usage_limit",
                    models.PositiveIntegerField(
                        default=1,
                        help_text="Maximum redemptions per user.",
                        verbose_name="per-user usage limit",
                    ),
                ),
                (
                    "usage_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Denormalized counter of total redemptions.",
                        verbose_name="current usage count",
                    ),
                ),
                (
                    "audience_type",
                    models.CharField(
                        choices=[("all", "All Users"), ("specific_users", "Specific Users")],
                        default="all",
                        max_length=20,
                        verbose_name="audience type",
                    ),
                ),
                (
                    "eligible_users",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Only relevant when audience_type is SPECIFIC_USERS.",
                        related_name="eligible_coupons",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="eligible users",
                    ),
                ),
                (
                    "excluded_products",
                    models.ManyToManyField(
                        blank=True,
                        related_name="excluded_coupons",
                        to="products.product",
                        verbose_name="excluded products",
                    ),
                ),
                (
                    "included_brands",
                    models.ManyToManyField(
                        blank=True,
                        related_name="coupons",
                        to="products.brand",
                        verbose_name="included brands",
                    ),
                ),
                (
                    "included_categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="coupons",
                        to="categories.category",
                        verbose_name="included categories",
                    ),
                ),
                (
                    "included_products",
                    models.ManyToManyField(
                        blank=True,
                        related_name="included_coupons",
                        to="products.product",
                        verbose_name="included products",
                    ),
                ),
            ],
            options={
                "verbose_name": "Coupon",
                "verbose_name_plural": "Coupons",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CouponUsage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4) for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "discount_amount",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="discount amount applied (Rial)",
                    ),
                ),
                (
                    "redeemed_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="redeemed at"
                    ),
                ),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usages",
                        to="promotions.coupon",
                        verbose_name="coupon",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="coupon_usages",
                        to="orders.order",
                        verbose_name="order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coupon_usages",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="user",
                    ),
                ),
            ],
            options={
                "verbose_name": "Coupon Usage",
                "verbose_name_plural": "Coupon Usages",
                "ordering": ["-redeemed_at"],
            },
        ),
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4) for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("name", models.CharField(max_length=255, verbose_name="promotion name")),
                ("slug", models.SlugField(max_length=255, unique=True, verbose_name="slug")),
                ("description", models.TextField(blank=True, verbose_name="description")),
                (
                    "discount_type",
                    models.CharField(
                        choices=[("percentage", "Percentage"), ("fixed_amount", "Fixed Amount")],
                        max_length=20,
                        verbose_name="discount type",
                    ),
                ),
                (
                    "discount_value",
                    models.DecimalField(
                        decimal_places=0,
                        help_text="Percentage (0-100) when type is percentage, or fixed Rial amount when type is fixed_amount.",
                        max_digits=12,
                        verbose_name="discount value",
                    ),
                ),
                (
                    "max_discount_amount",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        help_text="Caps the discount for percentage-type promotions.",
                        max_digits=12,
                        null=True,
                        verbose_name="maximum discount amount (Rial)",
                    ),
                ),
                ("start_at", models.DateTimeField(blank=True, null=True, verbose_name="start at")),
                ("end_at", models.DateTimeField(blank=True, null=True, verbose_name="end at")),
                (
                    "is_active",
                    models.BooleanField(db_index=True, default=False, verbose_name="is active"),
                ),
                (
                    "priority",
                    models.IntegerField(
                        default=0,
                        help_text="Lower number = higher priority. Used for conflict resolution.",
                        verbose_name="priority",
                    ),
                ),
                (
                    "excluded_products",
                    models.ManyToManyField(
                        blank=True,
                        related_name="excluded_promotions",
                        to="products.product",
                        verbose_name="excluded products",
                    ),
                ),
                (
                    "included_brands",
                    models.ManyToManyField(
                        blank=True,
                        related_name="promotions",
                        to="products.brand",
                        verbose_name="included brands",
                    ),
                ),
                (
                    "included_categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="promotions",
                        to="categories.category",
                        verbose_name="included categories",
                    ),
                ),
                (
                    "included_products",
                    models.ManyToManyField(
                        blank=True,
                        related_name="included_promotions",
                        to="products.product",
                        verbose_name="included products",
                    ),
                ),
            ],
            options={
                "verbose_name": "Promotion",
                "verbose_name_plural": "Promotions",
                "ordering": ["priority", "-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="coupon",
            index=models.Index(
                fields=["is_active", "start_at", "end_at"], name="idx_coupon_active_window"
            ),
        ),
        migrations.AddConstraint(
            model_name="coupon",
            constraint=models.CheckConstraint(
                condition=models.Q(("discount_value__gt", 0)), name="coupon_discount_value_gt_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="coupon",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("discount_type", "fixed_amount"), ("discount_value__lte", 100), _connector="OR"
                ),
                name="coupon_percentage_lte_100",
            ),
        ),
        migrations.AddConstraint(
            model_name="coupon",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("max_discount_amount__isnull", True),
                    ("max_discount_amount__gte", 0),
                    _connector="OR",
                ),
                name="coupon_max_discount_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="coupon",
            constraint=models.CheckConstraint(
                condition=models.Q(("min_order_subtotal__gte", 0)),
                name="coupon_min_order_subtotal_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="coupon",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("start_at__isnull", True),
                    ("end_at__isnull", True),
                    ("start_at__lt", models.F("end_at")),
                    _connector="OR",
                ),
                name="coupon_start_before_end",
            ),
        ),
        migrations.AddIndex(
            model_name="couponusage",
            index=models.Index(fields=["coupon", "user"], name="idx_coupon_usage_coupon_user"),
        ),
        migrations.AddConstraint(
            model_name="couponusage",
            constraint=models.CheckConstraint(
                condition=models.Q(("discount_amount__gte", 0)), name="coupon_usage_discount_gte_0"
            ),
        ),
        migrations.AddIndex(
            model_name="promotion",
            index=models.Index(
                fields=["is_active", "start_at", "end_at"], name="idx_promo_active_window"
            ),
        ),
        migrations.AddConstraint(
            model_name="promotion",
            constraint=models.CheckConstraint(
                condition=models.Q(("discount_value__gt", 0)), name="promo_discount_value_gt_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="promotion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("discount_type", "fixed_amount"), ("discount_value__lte", 100), _connector="OR"
                ),
                name="promo_percentage_lte_100",
            ),
        ),
        migrations.AddConstraint(
            model_name="promotion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("max_discount_amount__isnull", True),
                    ("max_discount_amount__gte", 0),
                    _connector="OR",
                ),
                name="promo_max_discount_gte_0",
            ),
        ),
        migrations.AddConstraint(
            model_name="promotion",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("start_at__isnull", True),
                    ("end_at__isnull", True),
                    ("start_at__lt", models.F("end_at")),
                    _connector="OR",
                ),
                name="promo_start_before_end",
            ),
        ),
    ]
