# Generated by Django 5.2.17 on 2026-08-25 06:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminNotification",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4) for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("title", models.CharField(max_length=255, verbose_name="title")),
                ("message", models.TextField(verbose_name="message")),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("ORDER", "Order Event"),
                            ("STOCK", "Inventory Alert"),
                            ("REVIEW", "Review Moderation"),
                            ("PAYMENT", "Payment Transaction"),
                            ("SYSTEM", "System Notice"),
                        ],
                        db_index=True,
                        default="SYSTEM",
                        max_length=50,
                        verbose_name="notification type",
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(db_index=True, default=False, verbose_name="is read"),
                ),
                (
                    "action_url",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="action URL"
                    ),
                ),
                (
                    "resource_id",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="resource ID"
                    ),
                ),
            ],
            options={
                "verbose_name": "Admin Notification",
                "verbose_name_plural": "Admin Notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4) for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "key",
                    models.CharField(
                        db_index=True, max_length=100, unique=True, verbose_name="setting key"
                    ),
                ),
                ("value", models.JSONField(default=dict, verbose_name="setting value")),
                ("description", models.TextField(blank=True, verbose_name="description")),
            ],
            options={
                "verbose_name": "System Setting",
                "verbose_name_plural": "System Settings",
                "ordering": ["key"],
            },
        ),
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4) for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "user_email",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="actor email snapshot"
                    ),
                ),
                ("action", models.CharField(db_index=True, max_length=100, verbose_name="action")),
                (
                    "resource_type",
                    models.CharField(db_index=True, max_length=100, verbose_name="resource type"),
                ),
                (
                    "resource_id",
                    models.CharField(blank=True, max_length=255, verbose_name="resource id"),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(blank=True, null=True, verbose_name="IP Address"),
                ),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="sanitized metadata"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_logs",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="actor",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Log",
                "verbose_name_plural": "Audit Logs",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["resource_type", "resource_id"], name="idx_audit_resource"
                    ),
                    models.Index(fields=["action", "created_at"], name="idx_audit_action_created"),
                ],
            },
        ),
    ]
