# Generated by Django 5.2.16 on 2026-08-26 08:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0002_order_order_subtotal_gte_0_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShippingZone",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4) for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("name", models.CharField(max_length=150, unique=True, verbose_name="zone name")),
                (
                    "provinces",
                    models.JSONField(
                        default=list,
                        help_text="List of province names covered by this zone (e.g. ['تهران', 'البرز']).",
                        verbose_name="provinces",
                    ),
                ),
                (
                    "cities",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="Optional list of specific cities covered. Leave empty for all cities in province.",
                        verbose_name="cities",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="is active")),
            ],
            options={
                "verbose_name": "Shipping Zone",
                "verbose_name_plural": "Shipping Zones",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="ShippingMethod",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4) for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("name", models.CharField(max_length=200, verbose_name="name")),
                ("code", models.SlugField(unique=True, verbose_name="code")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="description"),
                ),
                (
                    "base_rate",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        help_text="Base flat shipping fee in Iranian Rial.",
                        max_digits=12,
                        verbose_name="base rate (Rial)",
                    ),
                ),
                (
                    "free_shipping_threshold",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        help_text="Order subtotal required for this method to become free of charge.",
                        max_digits=12,
                        null=True,
                        verbose_name="free shipping threshold (Rial)",
                    ),
                ),
                (
                    "estimated_days_min",
                    models.PositiveIntegerField(
                        default=1, verbose_name="min estimated delivery days"
                    ),
                ),
                (
                    "estimated_days_max",
                    models.PositiveIntegerField(
                        default=3, verbose_name="max estimated delivery days"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="is active")),
                ("sort_order", models.PositiveIntegerField(default=0, verbose_name="sort order")),
            ],
            options={
                "verbose_name": "Shipping Method",
                "verbose_name_plural": "Shipping Methods",
                "ordering": ["sort_order", "base_rate"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("base_rate__gte", 0)), name="shipping_base_rate_gte_0"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Shipment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4) for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "tracking_code",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="tracking code",
                    ),
                ),
                (
                    "carrier_name",
                    models.CharField(
                        default="پیک اختصاصی پارادوکس", max_length=100, verbose_name="carrier name"
                    ),
                ),
                (
                    "shipping_fee",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        max_digits=12,
                        verbose_name="shipping fee (Rial)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Processing"),
                            ("label_created", "Shipping Label Created"),
                            ("in_transit", "In Transit / Handed over to Courier"),
                            ("out_for_delivery", "Out for Delivery"),
                            ("delivered", "Delivered to Customer"),
                            ("failed", "Delivery Failed / Returned"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=25,
                        verbose_name="shipment status",
                    ),
                ),
                (
                    "shipped_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="shipped at"),
                ),
                (
                    "delivered_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="delivered at"),
                ),
                ("notes", models.TextField(blank=True, null=True, verbose_name="delivery notes")),
                (
                    "order",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="shipment",
                        to="orders.order",
                        verbose_name="order",
                    ),
                ),
                (
                    "shipping_method",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shipments",
                        to="shipping.shippingmethod",
                        verbose_name="shipping method",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shipment",
                "verbose_name_plural": "Shipments",
                "ordering": ["-created_at"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("shipping_fee__gte", 0)),
                        name="shipment_shipping_fee_gte_0",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ShippingZoneRate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4) for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "rate_override",
                    models.DecimalField(
                        blank=True,
                        decimal_places=0,
                        help_text="Overrides base shipping rate if specified.",
                        max_digits=12,
                        null=True,
                        verbose_name="rate override (Rial)",
                    ),
                ),
                (
                    "additional_fee",
                    models.DecimalField(
                        decimal_places=0,
                        default=0,
                        help_text="Extra surcharge added on top of base rate for this zone.",
                        max_digits=12,
                        verbose_name="additional fee (Rial)",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="is active")),
                (
                    "method",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="zone_rates",
                        to="shipping.shippingmethod",
                        verbose_name="shipping method",
                    ),
                ),
                (
                    "zone",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates",
                        to="shipping.shippingzone",
                        verbose_name="zone",
                    ),
                ),
            ],
            options={
                "verbose_name": "Shipping Zone Rate",
                "verbose_name_plural": "Shipping Zone Rates",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("zone", "method"), name="unique_zone_method_rate"
                    )
                ],
            },
        ),
    ]
