# Generated by Django 5.2.17 on 2026-08-29 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shipping", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shipment",
            name="carrier_name",
            field=models.CharField(
                default="Paradox Express Fleet", max_length=100, verbose_name="carrier name"
            ),
        ),
    ]
