# Generated by Django 5.2.17 on 2026-09-01 13:21

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0003_productcomment"),
        ("reviews", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4) for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("question", models.TextField(verbose_name="question text")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Moderation"),
                            ("APPROVED", "Approved / Public"),
                            ("REJECTED", "Rejected"),
                            ("HIDDEN", "Hidden"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                        verbose_name="moderation status",
                    ),
                ),
                (
                    "rejection_reason",
                    models.TextField(blank=True, null=True, verbose_name="rejection reason"),
                ),
            ],
            options={
                "verbose_name": "Product Question",
                "verbose_name_plural": "Product Questions",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="QuestionAnswer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4) for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("answer", models.TextField(verbose_name="answer text")),
                (
                    "is_official",
                    models.BooleanField(default=True, verbose_name="is official staff answer"),
                ),
            ],
            options={
                "verbose_name": "Question Answer",
                "verbose_name_plural": "Question Answers",
            },
        ),
        migrations.CreateModel(
            name="QuestionReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4) for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("reason", models.CharField(max_length=50, verbose_name="report reason")),
                (
                    "details",
                    models.TextField(blank=True, null=True, verbose_name="additional details"),
                ),
                (
                    "status",
                    models.CharField(
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                        verbose_name="report status",
                    ),
                ),
            ],
            options={
                "verbose_name": "Question Report",
                "verbose_name_plural": "Question Reports",
            },
        ),
        migrations.CreateModel(
            name="ReviewImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4) for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("image", models.ImageField(upload_to="reviews/%Y/%m/", verbose_name="image")),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="reviews/thumbs/%Y/%m/",
                        verbose_name="thumbnail",
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="original filename"
                    ),
                ),
                (
                    "file_size",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="file size in bytes"
                    ),
                ),
                (
                    "mime_type",
                    models.CharField(
                        blank=True, max_length=50, null=True, verbose_name="MIME type"
                    ),
                ),
                ("is_processed", models.BooleanField(default=False, verbose_name="is processed")),
                (
                    "sort_order",
                    models.PositiveSmallIntegerField(default=0, verbose_name="sort order"),
                ),
            ],
            options={
                "verbose_name": "Review Image",
                "verbose_name_plural": "Review Images",
                "ordering": ["sort_order", "created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReviewReport",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4) for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("SPAM", "Spam / Commercial Solicitation"),
                            ("OFFENSIVE", "Offensive / Abusive Language"),
                            ("FAKE", "Fake or Inauthentic Review"),
                            ("IRRELEVANT", "Irrelevant to Artifact Quality"),
                            ("INAPPROPRIATE_IMAGE", "Inappropriate Image Attachment"),
                            ("OTHER", "Other Policy Violation"),
                        ],
                        max_length=50,
                        verbose_name="report reason",
                    ),
                ),
                (
                    "details",
                    models.TextField(blank=True, null=True, verbose_name="additional details"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending Review"),
                            ("RESOLVED", "Resolved / Action Taken"),
                            ("DISMISSED", "Dismissed / False Alarm"),
                        ],
                        db_index=True,
                        default="PENDING",
                        max_length=20,
                        verbose_name="report status",
                    ),
                ),
            ],
            options={
                "verbose_name": "Review Report",
                "verbose_name_plural": "Review Reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReviewResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4) for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("response_text", models.TextField(verbose_name="response text")),
                (
                    "is_official",
                    models.BooleanField(default=True, verbose_name="is official team response"),
                ),
            ],
            options={
                "verbose_name": "Review Staff Response",
                "verbose_name_plural": "Review Staff Responses",
            },
        ),
        migrations.CreateModel(
            name="ReviewVote",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4) for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                ("is_helpful", models.BooleanField(default=True, verbose_name="is helpful")),
            ],
            options={
                "verbose_name": "Review Vote",
                "verbose_name_plural": "Review Votes",
            },
        ),
        migrations.AddField(
            model_name="review",
            name="cons",
            field=models.JSONField(blank=True, default=list, verbose_name="cons / critiques"),
        ),
        migrations.AddField(
            model_name="review",
            name="helpful_count",
            field=models.PositiveIntegerField(default=0, verbose_name="helpful votes count"),
        ),
        migrations.AddField(
            model_name="review",
            name="pros",
            field=models.JSONField(blank=True, default=list, verbose_name="pros / highlights"),
        ),
        migrations.AddField(
            model_name="review",
            name="rejection_reason",
            field=models.TextField(blank=True, null=True, verbose_name="rejection reason"),
        ),
        migrations.AddField(
            model_name="review",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending Moderation"),
                    ("APPROVED", "Approved / Public"),
                    ("REJECTED", "Rejected"),
                    ("HIDDEN", "Hidden"),
                ],
                db_index=True,
                default="PENDING",
                max_length=20,
                verbose_name="moderation status",
            ),
        ),
        migrations.AddField(
            model_name="review",
            name="unhelpful_count",
            field=models.PositiveIntegerField(default=0, verbose_name="unhelpful votes count"),
        ),
        migrations.AlterField(
            model_name="review",
            name="is_verified_purchase",
            field=models.BooleanField(
                db_index=True, default=False, verbose_name="is verified purchase"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(
                fields=["product", "status", "-created_at"], name="idx_rev_prod_status_created"
            ),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["user", "-created_at"], name="idx_rev_user_created"),
        ),
        migrations.AddIndex(
            model_name="review",
            index=models.Index(fields=["product", "rating"], name="idx_rev_prod_rating"),
        ),
        migrations.AddField(
            model_name="productquestion",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="products.product",
                verbose_name="product",
            ),
        ),
        migrations.AddField(
            model_name="productquestion",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="product_questions",
                to=settings.AUTH_USER_MODEL,
                verbose_name="inquirer",
            ),
        ),
        migrations.AddField(
            model_name="questionanswer",
            name="question",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="answer",
                to="reviews.productquestion",
                verbose_name="question",
            ),
        ),
        migrations.AddField(
            model_name="questionanswer",
            name="staff_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="question_staff_answers",
                to=settings.AUTH_USER_MODEL,
                verbose_name="staff member",
            ),
        ),
        migrations.AddField(
            model_name="questionreport",
            name="question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="reviews.productquestion",
                verbose_name="question",
            ),
        ),
        migrations.AddField(
            model_name="questionreport",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="question_reports",
                to=settings.AUTH_USER_MODEL,
                verbose_name="reporting user",
            ),
        ),
        migrations.AddField(
            model_name="reviewimage",
            name="review",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="reviews.review",
                verbose_name="review",
            ),
        ),
        migrations.AddField(
            model_name="reviewreport",
            name="review",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reports",
                to="reviews.review",
                verbose_name="review",
            ),
        ),
        migrations.AddField(
            model_name="reviewreport",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review_reports",
                to=settings.AUTH_USER_MODEL,
                verbose_name="reporting user",
            ),
        ),
        migrations.AddField(
            model_name="reviewresponse",
            name="review",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="staff_response",
                to="reviews.review",
                verbose_name="review",
            ),
        ),
        migrations.AddField(
            model_name="reviewresponse",
            name="staff_user",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="review_staff_responses",
                to=settings.AUTH_USER_MODEL,
                verbose_name="staff member",
            ),
        ),
        migrations.AddField(
            model_name="reviewvote",
            name="review",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="votes",
                to="reviews.review",
                verbose_name="review",
            ),
        ),
        migrations.AddField(
            model_name="reviewvote",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="review_votes",
                to=settings.AUTH_USER_MODEL,
                verbose_name="user",
            ),
        ),
        migrations.AddIndex(
            model_name="productquestion",
            index=models.Index(
                fields=["product", "status", "-created_at"], name="idx_q_prod_status_created"
            ),
        ),
        migrations.AddIndex(
            model_name="productquestion",
            index=models.Index(fields=["user", "-created_at"], name="idx_q_user_created"),
        ),
        migrations.AddConstraint(
            model_name="questionreport",
            constraint=models.UniqueConstraint(
                fields=("question", "user"), name="unique_question_user_report"
            ),
        ),
        migrations.AddConstraint(
            model_name="reviewreport",
            constraint=models.UniqueConstraint(
                fields=("review", "user"), name="unique_review_user_report"
            ),
        ),
        migrations.AddConstraint(
            model_name="reviewvote",
            constraint=models.UniqueConstraint(
                fields=("review", "user"), name="unique_review_user_vote"
            ),
        ),
    ]
