# Generated by Django 5.2.16 on 2026-08-06 07:29

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier (UUID v4) for this record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, db_index=True, verbose_name="Created At"
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="Updated At")),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=0,
                        help_text="Payment amount in Iranian Rial.",
                        max_digits=12,
                        verbose_name="amount (Rial)",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("succeeded", "Succeeded"),
                            ("failed", "Failed"),
                            ("refunded", "Refunded"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                        verbose_name="status",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("online", "Online Gateway"),
                            ("wallet", "User Wallet"),
                            ("cod", "Cash on Delivery"),
                        ],
                        default="online",
                        max_length=20,
                        verbose_name="payment method",
                    ),
                ),
                (
                    "gateway",
                    models.CharField(
                        blank=True,
                        help_text="e.g., zarinpal, pasargad",
                        max_length=50,
                        null=True,
                        verbose_name="payment gateway",
                    ),
                ),
                (
                    "transaction_id",
                    models.CharField(
                        blank=True,
                        db_index=True,
                        max_length=100,
                        null=True,
                        unique=True,
                        verbose_name="transaction ID",
                    ),
                ),
                (
                    "gateway_response",
                    models.JSONField(blank=True, null=True, verbose_name="gateway raw response"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="payments",
                        to="orders.order",
                        verbose_name="order",
                    ),
                ),
            ],
            options={
                "verbose_name": "Payment",
                "verbose_name_plural": "Payments",
                "ordering": ["-created_at"],
            },
        ),
    ]
