# Generated by Django 5.2.17 on 2026-08-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_order_order_subtotal_gte_0_and_more"),
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="idempotency_key",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="Unique key supplied by client to prevent duplicate payment submissions.",
                max_length=255,
                null=True,
                unique=True,
                verbose_name="idempotency key",
            ),
        ),
        migrations.AddConstraint(
            model_name="payment",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount__gte", 0)), name="payment_amount_gte_0"
            ),
        ),
    ]
