# Generated by Django 5.2.17 on 2026-08-17 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="product",
            constraint=models.CheckConstraint(
                condition=models.Q(("base_price__gte", 0)), name="product_base_price_gte_0"
            ),
        ),
        migrations.AddConstraint(
            model_name="productvariant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("price_override__isnull", True), ("price_override__gte", 0), _connector="OR"
                ),
                name="variant_price_override_gte_0",
            ),
        ),
    ]
