# Generated by Django 5.2.17 on 2026-09-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("categories", "0001_initial"),
        ("products", "0003_productcomment"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="product",
            index=models.Index(
                fields=["is_active", "-is_featured", "-created_at"], name="prod_catalog_sort_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="product",
            index=models.Index(fields=["base_price"], name="prod_base_price_idx"),
        ),
        migrations.AddIndex(
            model_name="productimage",
            index=models.Index(fields=["product", "is_primary"], name="prod_img_primary_idx"),
        ),
    ]
